name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: k8s

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
          
      - name: Build Docker Image
        run: |
          sudo docker build -t ${{ secrets.DOCKER_USERNAME }}/k8s-nginx-html:1 .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/k8s-nginx-html:1
        
      - name: Docker logout
        run: | 
          docker logout

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      # - name: Remove Kubernetes if exists
      #   run: |
      #     kubectl delete -f deployment.yaml -n nginx-k8s
      #     kubectl delete -f service.yaml -n nginx-k8s        

      - name: Deploy to Kubernetes
        run: |
          kubectl create namespace nginx-k8s --dry-run=client -o yaml | kubectl apply -f -
          kubectl apply -f deployment.yaml -n nginx-k8s
          kubectl apply -f service.yaml -n nginx-k8s

      - name: Verify Deployment
        run: kubectl get pods -n nginx-k8s && kubectl get svc -n nginx-k8s